In [13]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,SGDRegressor
import random
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [7]:
x,y = load_diabetes(return_X_y=True)

In [8]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3)

In [9]:
xtrain.shape

(309, 10)

In [10]:
ytrain.shape

(309,)

In [11]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [44]:
ypred = lr.predict(xtest)
print(ypred.shape)
r2_score(ytest,ypred)

(133,)


0.5170088472555245

In [61]:
lr.coef_

array([  25.80093193, -216.96122521,  572.08276089,  300.88444325,
       -834.63034111,  494.22454957,  139.23856238,  177.67858304,
        758.59710683,   95.32530788])

In [89]:
lr.intercept_

152.89991263634897

# Creating Mini batch Gradient descent from scratch

In [84]:
class MBGD:
    def __init__(self,lr=0.01,epochs=100,batch_size=10):
        self.coeff = 0
        self.intercept = 0
        self.lr = lr
        self.epochs = epochs
        self.batch_size = batch_size
    
    def fit(self,xtrain,ytrain):
         #init coeff and intercepts
        self.coeff = np.ones(xtrain.shape[1])
        self.intercept = 0
        for i in range(self.epochs):
            for j in range(int(xtrain.shape[0]/self.batch_size)):
                idx = random.sample(range(xtrain.shape[0]),self.batch_size)
                yhat = np.dot(xtrain[idx],self.coeff) + self.intercept
                
                intercept_der = -2*np.mean(ytrain[idx]-yhat)
                self.intercept = self.intercept - (self.lr * intercept_der)
                
                coeff_der = -2*np.dot((ytrain[idx]-yhat),xtrain[idx])
                self.coeff = self.coeff - (self.lr*coeff_der)
        print(self.coeff ,self.intercept)    
                
    def predict(self,xtest):
        return np.dot(xtest,self.coeff) + self.intercept
                    
        

In [126]:
mbdg = MBGD(lr = 0.01,epochs=50,batch_size=int(xtrain.shape[0]/30))

In [127]:
mbdg.fit(xtrain,ytrain)

[  58.27275389  -57.50519992  340.93673323  221.28780127   12.67050111
  -20.21207766 -177.90762593  140.08029106  274.57411314  155.00030152] 152.04787123207745


In [128]:
y_pred = mbdg.predict(xtest)
y_pred.shape

(133,)

In [129]:
r2_score(ytest,y_pred)

0.4708457345485607

# Implementing mini batch gradient in sklearn

In [105]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [116]:
batch_size = 35

for i in range(batch_size):
    idx = random.sample(range(xtrain.shape[0]),batch_size)
    sgd.partial_fit(xtrain[idx],ytrain[idx])

In [117]:
sgd.coef_

array([  36.13416426, -110.47832947,  421.22993597,  263.69371876,
        -20.89792599,  -63.97879588, -200.11664293,  146.96287063,
        313.60371844,  145.62975464])

In [118]:
sgd.intercept_

array([140.2873273])

In [119]:
ypredict = sgd.predict(xtest)

In [120]:
r2_score(ytest,ypredict)

0.4788670350972051